### ISSUE TITLE
Add E2E tests using some automated simulator

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/shoot-i-smoke#19]
It all started as a weekend project, so I didn't write tests.

Now people are starting to use this app, so it would be wise to make it a serious project.

**Comment by PepijnTrampe** [comment]
What me cool likes is if you add a map using google maps make a overlay that wil show you the air quality like a weather overlay

**Comment by amaurymartiny** [comment]
We sometimes have bugs on some devices that don't show the cigarettes correctly. It would be nice to have e2e tests (they don't need to be complex) on multiple devices. Ideas:
- https://github.com/wix/Detox
- https://www.browserstack.com/app-automate

**Comment by AlanCalvillo** [comment]
Are you guys considering use just Detox or are you open to different libraries (Cypress or Webrdiverio)?

**Comment by amaurymartiny** [comment]
I'm definitely open to libraries too, I just don't have much experience e2e testing mobile apps.

The only requirement is that tests are in JS/TS.

**Comment by GianOrtiz** [comment]
Hi, can I work on this one?

**Comment by amaurymartiny** [comment]
@GianOrtiz, yeah, sure, please go ahead! I just assigned you.

So for the beginning, a simple test would do, like "it should reach the homepage and show some cigarettes"

This issue is mostly about the e2e setup.
