### ISSUE TITLE
Add daily/weekly/monthly notifications

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/shoot-i-smoke#236]
The idea here is to show regular notifications on the user's phone, to remind him/her of the number of cigarettes he/she is smoking.

We would have the following options:
- daily notification
- weekly notification
- monthly notification
- ~pollution peak notification (notification when pollution is higher than recommended)~ leave this for later)

This user's preference should be stored in AsyncStorage. The UI for now is not decided, so a simple [Picker](https://facebook.github.io/react-native/docs/picker) in the About.tsx page would do.

If it's daily, we can show the notification at 10am. Weekly: Sunday 10pm. Monthly: 1st day of each month at 10 am.

Docs: https://docs.expo.io/versions/v35.0.0/sdk/notifications/

**Comment by kartik-budhiraja** [comment]
@amaurymartiny  I would love to work on this issue if it's available.

**Comment by amaurymartiny** [comment]
Yes, of course! I just assigned you, ping me here if you any help!

**Comment by matepapp** [comment]
@kartik-budhiraja can I help somehow? are you still working on the issue?

**Comment by kartik-budhiraja** [comment]
@matepapp I am going to look into this issue this week. I will let you know if we can split up the work if you want to help too.

**Comment by 97hknl** [comment]
Wow, cool idea! I would love to work on this issue as well !!

**Comment by amaurymartiny** [comment]
It's been 9 days and I didn't hear back from @kartik-budhiraja, so @97hknl I guess you can take it.

Unless @matepapp is still interested in doing it?

**Comment by matepapp** [comment]
you can work on it @97hknl 👍

**Comment by kartik-budhiraja** [comment]
@amaurymartiny , @97hknl I am currently in progress on this issue, will create a PR today, sorry for the delay!

**Comment by 97hknl** [comment]
> you can work on it @97hknl 👍

I am trying to set up my environment. What should I fill in the below params in app.json?

"organization": "YOUR_SENTRY_ORG",
"project": "YOUR_SENTRY_PROJECT",
"authToken": "null"

which are all properties of hooks beneath the githubUrl.

**Comment by amaurymartiny** [comment]
You can leave them as-is, they are only needed for publishing the app

**Comment by 97hknl** [comment]
I have troubles openinig the app in the emulator, on load, I get an error called "Invalid Dsn" with a huge stack trace. Any idea how to fix this?

**Comment by amaurymartiny** [comment]
Hey, yes. Could you put `null` (without quotes) to all fields in `app.json` where you didn't put tokens? In particular to the `sentryPublicDsn` field, which causes this error.

**Comment by 97hknl** [comment]
> Hey, yes. Could you put `null` (without quotes) to all fields in `app.json` where you didn't put tokens? In particular to the `sentryPublicDsn` field, which causes this error.
> 
> Could you create a new issue, or use https://spectrum.chat/shootismoke?tab=posts for other questions? Thanks!

I still get the same error, after setting everything to null. Should I create a new issue for this?

**Comment by amaurymartiny** [comment]
> Should I create a new issue for this?

Yes, I'll have a look into it!

**Comment by amaurymartiny** [comment]
@97hknl (and others) If you want to think about this comment: https://github.com/amaurymartiny/shoot-i-smoke/pull/292#pullrequestreview-302548152

Do you have other ideas on how to achieve this functionality?
