### ISSUE TITLE
Big number in share message

### ISSUE THREAD

**Issue by rlewicki** [amaurymartiny/shoot-i-smoke#240]
Platform: iOS
Version: 1.3.1
Description:
When you click share button to share the amount of cigarettes you smoked it shows very big floating point number (see image below).
![share_rounding](https://user-images.githubusercontent.com/10658394/66081467-4d6f2580-e568-11e9-964a-08d9d0eb3df0.png)

Suggested solution:
The number used in message share should be rounded to two position after the point.

**Comment by kermopajula** [comment]
https://github.com/amaurymartiny/shoot-i-smoke/pull/241
