### ISSUE TITLE
Allow users to change between miles and km

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/shoot-i-smoke#244]
Right now, it's showing `mi` when user's language is `en-US`, and `km` everywhere else.

My phone is en-US, but I use km. I would like to be able to configure that.

This setting should be saved in AsyncStorage.

For the UI, I think for now a simple [Switch](https://facebook.github.io/react-native/docs/switch) in the About.tsx screen would do.

**Comment by hendaoui** [comment]
Working on it :+1:

**Comment by hendaoui** [comment]
I'm not managing to get API keys, do you have test keys or can you help me generate new ones!

**Comment by amaurymartiny** [comment]
@hendaoui I just emailed you some new keys that I generated.

**Comment by matepapp** [comment]
hey @hendaoui, are you still working on it? I'm willing to help or implement if you don't

**Comment by hendaoui** [comment]
@matepapp feel free to work on it (unfortunately I didn't have enough time)
