### ISSUE TITLE
Add image sharing on Android

### ISSUE THREAD

**Issue by jamespearson** [amaurymartiny/shoot-i-smoke#247]
In #242 I added an image for sharing, but couldn't make the image sharing work on Android.

This would be a great jumping-in point for someone who is more Android first than me.

**Comment by ikakus** [comment]
Hi! I can try to help you with this one if you don't mind :)

**Comment by DragonSpirit** [comment]
Hi! Do you still need help with this? If so I want to grab it!

**Comment by amaurymartiny** [comment]
Yes, please do! I just assigned you.
