### ISSUE TITLE
Add `tsc --noEmit` while linting

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/shoot-i-smoke#248]
I would like to make this change:

https://github.com/amaurymartiny/shoot-i-smoke/blob/ccd33d5d6731c6dc0564fd9e8ccd6ce355f3bb43/package.json#L11

```diff
- "lint": "eslint --ext .ts,.tsx App", 
+ "lint": "tsc --noEmit && eslint --ext .ts,.tsx App", 
```

But right now, when running `node_modules/.bin/tsc --noEmit`, i have

```
// bunch of errors

Found 5 errors.
```

Errors are coming from typings in node_modules files. Investigate this, and find a way for TS to ignore those errors.

**Comment by idanyman** [comment]
Hey, this was rather easy to fix by just adding `--skipLibCheck` to the `tsc` command, hope you're fine with this solution!
