### ISSUE TITLE
Translate to Russian 🇷🇺

### ISSUE THREAD

**Issue by DragonSpirit** [amaurymartiny/shoot-i-smoke#256]
Hi! Which way is more preferable? Push json directly to repo or use poeditor.com?
I would like to help with it.

**Comment by amaurymartiny** [comment]
> Push json directly to repo

Push JSON is preferable. I'm only trying poeditor for people who don't know how to use git.

**Comment by DragonSpirit** [comment]
Okay, I will push new json file with localization in nearest future 💪
