### ISSUE TITLE
Create a web app

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/shoot-i-smoke#26]
Requested by some users on Google Play and Product Hunt.

Create a https://waqi.info, but with cigarettes number.

**Comment by marceloscoelho** [comment]
Would it be possible to use the code that you've already done for a Desktop version? Design-wise it wouldn't be a lot of work for me.

**Comment by amaurymartiny** [comment]
Although both are written in React, it is today not easy to use the same code in browser and in mobile app.

However for the web version I'm thinking we could make it somewhat different than the app? I.e. a map, like https://waqi.info, with cigarette count. No need for the "Change Location" feature in this case. There would be only the popup when the user clicks on a marker to design and to implement, it should be quite easy on my side too (~1 weekend).

**Comment by florenciasilva** [comment]
Can I start giving this a try? I was thinking in using the react-native code as reference but basically start from zero, recreating the mobile app as much as possible in terms of hierarchy of information and style. I would use create-react-app and .jsx

**Comment by amaurymartiny** [comment]
Hey @florenciasilva, that would actually be great! Right now Marcelo and I don't have much time to work on the web app, so we would really appreciate some help!

I created an empty repo with some basic boilerplate here: https://github.com/shootismoke/webapp. React is okay, but here are some technologies that I would like to use:
- Gatsby (instead of CRA), because SEO will play an important role in the web app.
- TypeScript (instead of .jsx), for all the benefits typings come with in my opiniion
- TailwindCSS: it's easily composable, and we don't need to commit to a huge UI library like Bootstrap or SUI.
- I added some basic linting tools too (basically Eslint + Prettier)

If you're okay with this stack, then feel free to start hacking on `/shootismoke/webapp`! Keep me in touch on how it's going, Marcelo and I would be glad to help you for anything 🚀 .

**Comment by marceloscoelho** [comment]
Hi @florenciasilva <https://github.com/florenciasilva>! As Amaury said,
feel free to ask for our help, I would love to explore the design of the
user experience on the web a little more.


Em qua, 2 de out de 2019 às 18:26, Amaury Martiny <notifications@github.com>
escreveu:

**Comment by florenciasilva** [comment]
> Hey @florenciasilva, that would actually be great! Right now Marcelo and I don't have much time to work on the web app, so we would really appreciate some help!
> 
> I created an empty repo with some basic boilerplate here: https://github.com/shootismoke/webapp. React is okay, but here are some technologies that I would like to use:
> 
> * Gatsby (instead of CRA), because SEO will play an important role in the web app.
> * TypeScript (instead of .jsx), for all the benefits typings come with in my opiniion
> * TailwindCSS: it's easily composable, and we don't need to commit to a huge UI library like Bootstrap or SUI.
> * I added some basic linting tools too (basically Eslint + Prettier)
> 
> If you're okay with this stack, then feel free to start hacking on `/shootismoke/webapp`! Keep me in touch on how it's going, Marcelo and I would be glad to help you for anything 🚀 .

This sounds great, its the perfect excuse for me to start with TypeScript. I'm gonna check the repo and continue the conversation over there!

**Comment by amaurymartiny** [comment]
Perfect!

➡️  For any newcomers who'd also like to work on the webapp, let's all move the conversation to https://github.com/shootismoke/webapp, and I'll close this issue.

Creating issues there or asking questions on https://spectrum.chat/shootismoke both work.
