### ISSUE TITLE
Invalid DSN on expo setup on Andriod Emulator

### ISSUE THREAD

**Issue by 97hknl** [amaurymartiny/shoot-i-smoke#286]
I tried to set-up the platform using the commands mentioned in the readme. Upon running yarn  start, the app starts up on phone and prints Invalid Dsn with the following stack trace:

Invalid Dsn
SentryError
    error.js:9:32
_fromString
    dsn.js:40:42
Dsn
    dsn.js:13:29
API
    api.js:10:40
BaseTransport
    base.js:10:34
FetchTransport
    fetch.js:11:47
_setupTransport
    backend.js:52:45
BaseBackend
    basebackend.js:15:26
ReactNativeBackend
    backend.js:12:8
BaseClient
    baseclient.js:50:41
ReactNativeClient
    client.js:15:25
initAndBind
    sdk.js:15:53
init
    sdk.js:59:16
init
    index.js:159:27
<unknown>
    App.tsx:36:14
loadModuleImplementation
    require.js:331:6
<unknown>
    index.tsx:17
loadModuleImplementation
    require.js:331:6
<unknown>
    AppEntry.js:4
loadModuleImplementation
    require.js:331:6
guardedLoadModule
    require.js:197:45
global code

**Comment by amaurymartiny** [comment]
Thanks for the issue!

Can you try if #287 solves the issue? Make sure to run `yarn start -c` to clear expo's cache.

**Comment by 97hknl** [comment]
I found the fix. One must have to set everything to null, except the "waqiToken", which must be filled with your api key, and also "apiKey" & "googleMapsApiKey" which must be left as "YOUR_KEY" , basically a string, not a null. This fixes the issue for me.
