### ISSUE TITLE
Add a bot to generate a screenshot of a random big city in the world

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/shoot-i-smoke#29]
And post this screenshot on social media. Or maybe the most polluted city in the world every day?

**Comment by marceloscoelho** [comment]
Great idea! I need to come up with some phrases to make this sound less robotic. The most polluted city in the world could generate problems for us though - people from the city getting angry and/or saying that the data is not correct, etc.

**Comment by amaurymartiny** [comment]
Yeah, true. So let's take maybe ~50 big cities in the world and randomly pick one and generate a screenshot.

**Comment by amaurymartiny** [comment]
Done: https://github.com/shootismoke/buffer-bot
