### ISSUE TITLE
Inform user when the Air Quality Station is too far?

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/shoot-i-smoke#30]
If the station is at >15km, the number of cigarettes shown is not really relevant to the user. Maybe we should show a popup or some message to inform the user about this?

Ideally there would be a CTA, but I can't think of anything concrete:
- "Buy AirMatrix!" sounds like an ad.
- "Help us install stations"?
- Maybe an information page, where we present AirMatrix but also other competitors: http://aqicn.org/sensor/ http://aqicn.org/products/

**Comment by marceloscoelho** [comment]
That is a good opportunity for monetizing the app. I agree it shouldn't be something aggressive such as "Buy AirMatrix", but present it in the way of "Help us install stations" seems very nice. It could be located under the Station name, right on the top but with discreet typography...
