### ISSUE TITLE
Air Quality Information

### ISSUE THREAD

**Issue by marceloscoelho** [amaurymartiny/shoot-i-smoke#34]
Right now the app has a very straightforward function: **display the number of cigarettes you are indirectly smoking daily**. With the app's growth of features and notoriety, would it be interesting to pivot it in into more complete Air Quality monitoring? Or would we lose focus doing that?

We could continue featuring the cigarettes information but putting more information below:

# S***! You've smoked 3 cigarettes today.
_PM2.5 **60**
PM10 **24**
O3 **31**
NO2 **14**
SO2 **2** 
CO **5**_

**Comment by amaurymartiny** [comment]
Good point.

The general feeling I have, when reading social media, is that we can broadly categorise the users into:
- the normal user: they are just curious about how many cigarettes they smoke. Best case scenario, they make a screenshot and share it
- the power user: they are concerned about air quality. I received a couple of emails/messages where people would ask me: "The station is at 5km, could you tell me where exactly it is?" or "I know the stations around me, and it's not in your db". For those, these info might be useful.

So I would suggest, on the homepage, we keep what we have. And maybe we could have another screen which focuses on the Air Quality Station (map, station name and these air quality info). Here's an example of WAQI has: http://aqicn.org/city/usa/wyoming/pinedale-gaseous/. It would be the same info (btw I like their "Primary pollutant: o3") but presented better.
