### ISSUE TITLE
Share Button with screenshot and link

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/shoot-i-smoke#35]
One of the strong points of this app is the design (thanks Marcelo!), esp. the homepage with the cigarettes.

I'm thinking, it would be perfect, in the "Share with friends" button, to share a screenshot + a link to download, instead of some plain text.

**Comment by viveksb007** [comment]
Hi I would like to take this up.

**Comment by amaurymartiny** [comment]
Hey @viveksb007, I would really appreciate this!

Is the issue description clear? Do you need some more indications?

**Comment by viveksb007** [comment]
Yes its clear. But to be sure when sharing the result. App should provide the below image + app download link right?

![photo_2019-10-02 18 35 11](https://user-images.githubusercontent.com/12713808/66046558-a7a9bf80-e543-11e9-8cc3-211bcb2cd98c.jpeg)

**Comment by amaurymartiny** [comment]
No, not the below image. It should be a screenshot of the home page, with the cigarette count, for example this image https://twitter.com/shootismoke/status/1077481829970649088.

Of course, it should take a screenshot of the actual screen on the home page, and share that image.

**Comment by viveksb007** [comment]
Yeah got it. Will give it a try.

**Comment by viveksb007** [comment]
Hi @amaurymartiny is there any channel where I can ask queries?
I am facing issues in running app on my Android device. Followed all the steps in README.
Just obtained API key for http://aqicn.org/api/ and wrote `"undefined"` for others. After building I am getting following error.

![photo_2019-10-02 22 12 03](https://user-images.githubusercontent.com/12713808/66063766-af785c80-e561-11e9-9725-15269a0db0b7.jpeg)

**Comment by amaurymartiny** [comment]
Hey Vivek! Sorry about that, it's my fault. Instead of `"undefined"`, it should just be `null` (without quotes) in `app.json`

I updated the README in consequence.

And you are right, there should be a channel to ask this sort of questions. I just created https://spectrum.chat/shootismoke!

**Comment by jamespearson** [comment]
Sorry, I started it as part of Hacktoberfest, and none of these comments were here when I last looked.
