### ISSUE TITLE
Change textColor to something more lighter

### ISSUE THREAD

**Issue by lucienbl** [amaurymartiny/shoot-i-smoke#68]
The text color is very hard to read (see screenshot below) 
![Screenshot_1555514057](https://user-images.githubusercontent.com/35530360/56299531-88091100-6134-11e9-89e6-5bba200fe5a6.png)
Is it possible to make it white to make it more "readable" (screenshot below)?
![Screenshot_1555514232](https://user-images.githubusercontent.com/35530360/56299631-b4249200-6134-11e9-92bb-8523706ad0f1.png)

**Comment by amaurymartiny** [comment]
Hey! This is actually a bug reported by some users, and I haven't been able to reproduce it, so it hasn't been worked on.

The background shouldn't be black, but white. All backgrounds in the app are either white or transparent, and the mp4's background is transparent too. So I didn't diagnose where the black color comes from.

I reported the bug on Expo https://github.com/expo/expo/issues/3861, but didn't get any progress.

**Comment by lucienbl** [comment]
Oh, then never mind my issue and hope this bug will be fixed soon by expo! :smiley:

**Comment by amaurymartiny** [comment]
Marcelo, who had this bug too, confirmed that it's working now. Cheers @lucienbl!
