### ISSUE TITLE
Translate to Spanish 🇪🇸

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/shoot-i-smoke#74]
We would appreciate some help for translating Sh**t! I Smoke to Spanish.

Here's a detailed guide on how to get started with translations: https://github.com/amaurymartiny/shoot-i-smoke/wiki/How-to-contribute-with-translations%3F

**Comment by OlgaMorales** [comment]
@amaurymartiny i'd like to help u

**Comment by amaurymartiny** [comment]
Nice, that would be very helpful! If you create a Pull Request with the Spanish translations (an `es.json`), I'll merge it asap.

Have a look at the wiki link on the 1st post. Ping me if you need help with which text goes where, or how to give your translations a try in the app.

**Comment by OlgaMorales** [comment]
@amaurymartiny it's my PR ready

**Comment by OlgaMorales** [comment]
@amaurymartiny done!

**Comment by amaurymartiny** [comment]
Thanks @OlgaMorales for #79. However, I found out that there were still a couple of strings in the app which were in English (it was my fault, I forgot to put them in `en.json`).

Would you like to continue working on the new ones? There are here: https://github.com/amaurymartiny/shoot-i-smoke/pull/81/files#diff-d74a2d947ea7e5d2e9ef65b18a8d5a70R42, in green. If yes, you can create a new PR for that.

**Comment by OlgaMorales** [comment]
sure @amaurymartiny

**Comment by lucienbl** [comment]
Don't you want using poeditor which would really be simpler? :joy:

**Comment by amaurymartiny** [comment]
@lucienbl I'll have a look at that, I promise!

**Comment by OlgaMorales** [comment]
new pull request done ! @amaurymartiny
