### ISSUE TITLE
Translate to Chinese 🇨🇳 / 翻译成中文

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/shoot-i-smoke#75]
We would appreciate some help for translating Sh**t! I Smoke to Chinese.

https://poeditor.com/join/project/iEsj0CSPGX

**Comment by yixxxichen** [comment]
I can provide some help if you don't mind.

**Comment by amaurymartiny** [comment]
Hey @yixxxichen, that would be very helpful! You can use our tool https://poeditor.com/join/project/iEsj0CSPGX, or just create a PR with a new json file following [this one](https://github.com/amaurymartiny/shoot-i-smoke/blob/master/App/localization/languages/en.json)
