### ISSUE TITLE
Change Location icon should not contain text

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/shoot-i-smoke#82]
https://github.com/amaurymartiny/shoot-i-smoke/blob/master/assets/images/changeLocation.png

Or else it's hard to translate! Instead, text should be below, as a RN `<Text>`

We already added FontAwesome in the app, so we just need to replace the image with FontAwesome location icon + orange circle background

**Comment by co16353sidak** [comment]
happy to work on this as my first issue here, please give me the go ahead for this @amaurymartiny

**Comment by amaurymartiny** [comment]
Yes, please go ahead @co16353sidak, thanks!

**Comment by co16353sidak** [comment]
@amaurymartiny
instead of implementing a font-awesome setup I thought it would be better if we used a svg with the removed bottom text line, this will aid us in using the pre-existing `<Image>` layout and by just replacing the png with the svg.
we get all the respnsiveness of svg without the text line. I could create a sample svg and show some mockups here if you want to go ahead with this idea 😃

**Comment by amaurymartiny** [comment]
Sounds good to me! Our designer Marcelo has already done the icon, here it is.

[location-bt.zip](https://github.com/amaurymartiny/shoot-i-smoke/files/3144696/location-bt.zip)

**Comment by lucienbl** [comment]
If you already have the icon as svg you can directly add the svg in the app which allows you to make the text translatable.

**Comment by amaurymartiny** [comment]
Hey @co16353sidak, are you still working on this? Do you need help?

**Comment by co16353sidak** [comment]
@amaurymartiny sorry for the delays, going through my exam
Give me another day for this 😄 
P.S: I will be pinging you if i get stuck

**Comment by kiranjd** [comment]
@amaurymartiny Just downloaded all zip file containing the location icons, you minify the images further using [tinypng](tinypng.com).
I have compressed the images by ~55% overall without compromising on quality.
Here are the compressed images, 
[location-png-minified.zip](https://github.com/amaurymartiny/shoot-i-smoke/files/3194222/location-png-minified.zip)

**Comment by amaurymartiny** [comment]
Thanks @kiranjd, I appreciate it!

But as @co16353sidak said, let's use SVG instead: it's smaller than png, and there's no worry of screen resolution.

**Comment by shakti97** [comment]
is this issue still incomplete or done but not marked closed?

**Comment by amaurymartiny** [comment]
No, it's incomplete
