### ISSUE TITLE
Styles Issue in Cigarettes

### ISSUE THREAD

**Issue by pkhodaveissi** [amaurymartiny/shoot-i-smoke#86]

**Comment by pkhodaveissi** [comment]
/App/Screens/Home/Cigarettes/Cigarettes.js

styles.single is not defined

**Comment by amaurymartiny** [comment]
Would you like to create a PR? Removing that line should do the trick

**Comment by pkhodaveissi** [comment]
I thought you were actually gonna apply some style there, otherwise It would've been a PR

**Comment by pkhodaveissi** [comment]
I will close this with a PR in a day

**Comment by amaurymartiny** [comment]
Closed by #87
